// Generated by https://quicktype.io

export interface PokemonListResponse {
  count: number;
  next: string;
  previous: null;
  results: SmallPokemon[];
}

export interface SmallPokemon {
  name: string;
  url: string;
  id: number;
  img: string;
}

//details image and id of the pokemon
// export interface PokemonDetails {
//   id: number;
//   sprites: Sprite;
// }

// export interface Sprite {
//   other: Others;
// }

// export interface DreamWorlds {
//   front_default: string;
// }

// export interface Others {
//   dream_world: DreamWorlds;
// }

